FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

RUN apt-get update && apt-get install -y unzip \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json /app/

COPY frontend/package.json /app/frontend/

RUN npm ci -w frontend

COPY ./frontend /app/frontend

WORKDIR /app/frontend

ARG VITE_API_URL
