// This file is auto-generated by @hey-api/openapi-ts

export const Body_items_upload_item_photosSchema = {
    properties: {
        files: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['files'],
    title: 'Body_items-upload_item_photos'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BrandCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'BrandCreate'
} as const;

export const BrandPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'BrandPublic'
} as const;

export const BrandUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'BrandUpdate'
} as const;

export const BrandsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BrandPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BrandsPublic'
} as const;

export const CartItemCreateSchema = {
    properties: {
        item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Id'
        },
        quantity: {
            type: 'integer',
            maximum: 999,
            minimum: 1,
            title: 'Quantity',
            default: 1
        }
    },
    type: 'object',
    required: ['item_id'],
    title: 'CartItemCreate'
} as const;

export const CartItemPublicSchema = {
    properties: {
        quantity: {
            type: 'integer',
            maximum: 999,
            minimum: 1,
            title: 'Quantity',
            default: 1
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Id'
        },
        item: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ItemPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'item_id'],
    title: 'CartItemPublic'
} as const;

export const CartItemUpdateSchema = {
    properties: {
        quantity: {
            type: 'integer',
            maximum: 999,
            minimum: 1,
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['quantity'],
    title: 'CartItemUpdate'
} as const;

export const CartItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CartItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        subtotal: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Subtotal'
        }
    },
    type: 'object',
    required: ['data', 'count', 'subtotal'],
    title: 'CartItemsPublic'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'CategoryPublic'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'CategoryUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        size_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Id'
        },
        brand_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        images: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Images'
        },
        stock: {
            type: 'integer',
            minimum: 0,
            title: 'Stock',
            default: 0
        },
        cost: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        size_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Id'
        },
        brand_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        images: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Images'
        },
        stock: {
            type: 'integer',
            minimum: 0,
            title: 'Stock',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        cost: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        brand: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BrandPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        size_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Id'
        },
        brand_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Id'
        },
        cost: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        stock: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stock'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrderCancelSchema = {
    properties: {
        reason: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['reason'],
    title: 'OrderCancel'
} as const;

export const OrderCreateSchema = {
    properties: {
        recipient_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Recipient Name'
        },
        phone: {
            type: 'string',
            maxLength: 32,
            minLength: 1,
            title: 'Phone'
        },
        address: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Address'
        },
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['recipient_name', 'phone', 'address'],
    title: 'OrderCreate'
} as const;

export const OrderItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        item_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Id'
        },
        title_snapshot: {
            type: 'string',
            title: 'Title Snapshot'
        },
        price_snapshot: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Price Snapshot'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['id', 'item_id', 'title_snapshot', 'price_snapshot', 'quantity'],
    title: 'OrderItemPublic'
} as const;

export const OrderPaySchema = {
    properties: {
        card_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Card Id'
        },
        card: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PaymentCardCreate'
                },
                {
                    type: 'null'
                }
            ]
        },
        save_card: {
            type: 'boolean',
            title: 'Save Card',
            default: false
        }
    },
    type: 'object',
    title: 'OrderPay'
} as const;

export const OrderPublicSchema = {
    properties: {
        recipient_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Recipient Name'
        },
        phone: {
            type: 'string',
            maxLength: 32,
            minLength: 1,
            title: 'Phone'
        },
        address: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Address'
        },
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        status: {
            '$ref': '#/components/schemas/OrderStatus'
        },
        total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total'
        },
        cancellation_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancellation Reason'
        },
        paid_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid At'
        },
        received_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Received At'
        },
        refunded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refunded At'
        },
        card_brand: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Card Brand'
        },
        card_last4: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Card Last4'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/OrderItemPublic'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['recipient_name', 'phone', 'address', 'id', 'user_id', 'status', 'total'],
    title: 'OrderPublic'
} as const;

export const OrderStatsBucketSchema = {
    properties: {
        bucket: {
            type: 'string',
            format: 'date-time',
            title: 'Bucket'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total'
        },
        average: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Average'
        }
    },
    type: 'object',
    required: ['bucket', 'count', 'total', 'average'],
    title: 'OrderStatsBucket'
} as const;

export const OrderStatsResponseSchema = {
    properties: {
        group_by: {
            type: 'string',
            enum: ['hour', 'day', 'month'],
            title: 'Group By'
        },
        start: {
            type: 'string',
            format: 'date-time',
            title: 'Start'
        },
        end: {
            type: 'string',
            format: 'date-time',
            title: 'End'
        },
        points: {
            items: {
                '$ref': '#/components/schemas/OrderStatsBucket'
            },
            type: 'array',
            title: 'Points'
        },
        summary: {
            '$ref': '#/components/schemas/OrderStatsSummary'
        }
    },
    type: 'object',
    required: ['group_by', 'start', 'end', 'points', 'summary'],
    title: 'OrderStatsResponse'
} as const;

export const OrderStatsSummarySchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        },
        total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total'
        },
        average: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Average'
        }
    },
    type: 'object',
    required: ['count', 'total', 'average'],
    title: 'OrderStatsSummary'
} as const;

export const OrderStatusSchema = {
    type: 'string',
    enum: ['NEW', 'PROCESSED', 'PAID', 'SHIPPED', 'DELIVERED', 'RECEIVED', 'REFUNDED', 'CANCELLED'],
    title: 'OrderStatus'
} as const;

export const OrderUpdateSchema = {
    properties: {
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OrderStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'OrderUpdate'
} as const;

export const OrdersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OrderPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OrdersPublic'
} as const;

export const PaymentCardCreateSchema = {
    properties: {
        card_number: {
            type: 'string',
            maxLength: 23,
            minLength: 12,
            title: 'Card Number'
        },
        exp_month: {
            type: 'integer',
            maximum: 12,
            minimum: 1,
            title: 'Exp Month'
        },
        exp_year: {
            type: 'integer',
            maximum: 2100,
            minimum: 2000,
            title: 'Exp Year'
        },
        cvc: {
            type: 'string',
            maxLength: 4,
            minLength: 3,
            title: 'Cvc'
        },
        cardholder_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'Cardholder Name'
        }
    },
    type: 'object',
    required: ['card_number', 'exp_month', 'exp_year', 'cvc', 'cardholder_name'],
    title: 'PaymentCardCreate'
} as const;

export const PaymentCardPublicSchema = {
    properties: {
        brand: {
            type: 'string',
            maxLength: 32,
            title: 'Brand'
        },
        last4: {
            type: 'string',
            maxLength: 4,
            minLength: 4,
            title: 'Last4'
        },
        exp_month: {
            type: 'integer',
            maximum: 12,
            minimum: 1,
            title: 'Exp Month'
        },
        exp_year: {
            type: 'integer',
            maximum: 2100,
            minimum: 2000,
            title: 'Exp Year'
        },
        cardholder_name: {
            type: 'string',
            maxLength: 255,
            title: 'Cardholder Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['brand', 'last4', 'exp_month', 'exp_year', 'cardholder_name', 'id'],
    title: 'PaymentCardPublic'
} as const;

export const PaymentCardsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PaymentCardPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PaymentCardsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SizeCountSchema = {
    properties: {
        size_id: {
            type: 'string',
            format: 'uuid',
            title: 'Size Id'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['size_id', 'count'],
    title: 'SizeCount'
} as const;

export const SizeCountsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SizeCount'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'SizeCountsPublic'
} as const;

export const SizeCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SizeCreate'
} as const;

export const SizePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'SizePublic'
} as const;

export const SizeUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'SizeUpdate'
} as const;

export const SizesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SizePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SizesPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        delivery_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivery Address'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        delivery_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivery Address'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        delivery_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivery Address'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        delivery_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivery Address'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WishlistItemCreateSchema = {
    properties: {
        item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Id'
        }
    },
    type: 'object',
    required: ['item_id'],
    title: 'WishlistItemCreate'
} as const;

export const WishlistItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Id'
        },
        item: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ItemPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'item_id'],
    title: 'WishlistItemPublic'
} as const;

export const WishlistItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WishlistItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WishlistItemsPublic'
} as const;