// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_items-upload_item_photos
 */
export type BodyItemsUploadItemPhotos = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CartItemCreate
 */
export type CartItemCreate = {
    /**
     * Item Id
     */
    item_id: string;
    /**
     * Quantity
     */
    quantity?: number;
};

/**
 * CartItemPublic
 */
export type CartItemPublic = {
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Item Id
     */
    item_id: string;
    item?: ItemPublic | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CartItemUpdate
 */
export type CartItemUpdate = {
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * CartItemsPublic
 */
export type CartItemsPublic = {
    /**
     * Data
     */
    data: Array<CartItemPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Subtotal
     */
    subtotal: string;
};

/**
 * CategoriesPublic
 */
export type CategoriesPublic = {
    /**
     * Data
     */
    data: Array<CategoryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * CategoryPublic
 */
export type CategoryPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Size Id
     */
    size_id?: string | null;
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Images
     */
    images?: Array<string>;
    /**
     * Stock
     */
    stock?: number;
    /**
     * Cost
     */
    cost?: number | string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Size Id
     */
    size_id?: string | null;
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Images
     */
    images?: Array<string>;
    /**
     * Stock
     */
    stock?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Cost
     */
    cost?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Size Id
     */
    size_id?: string | null;
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Cost
     */
    cost?: number | string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Stock
     */
    stock?: number | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OrderCreate
 */
export type OrderCreate = {
    /**
     * Recipient Name
     */
    recipient_name: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Address
     */
    address: string;
    /**
     * Comment
     */
    comment?: string | null;
};

/**
 * OrderItemPublic
 */
export type OrderItemPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Item Id
     */
    item_id: string | null;
    /**
     * Title Snapshot
     */
    title_snapshot: string;
    /**
     * Price Snapshot
     */
    price_snapshot: string;
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * OrderPublic
 */
export type OrderPublic = {
    /**
     * Recipient Name
     */
    recipient_name: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Address
     */
    address: string;
    /**
     * Comment
     */
    comment?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    status: OrderStatus;
    /**
     * Total
     */
    total: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Items
     */
    items?: Array<OrderItemPublic>;
};

/**
 * OrderStatus
 */
export type OrderStatus = 'NEW' | 'PROCESSED' | 'PAID' | 'SHIPPED' | 'DELIVERED';

/**
 * OrderUpdate
 */
export type OrderUpdate = {
    status?: OrderStatus | null;
};

/**
 * OrdersPublic
 */
export type OrdersPublic = {
    /**
     * Data
     */
    data: Array<OrderPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * SizeCount
 */
export type SizeCount = {
    /**
     * Size Id
     */
    size_id: string;
    /**
     * Count
     */
    count: number;
};

/**
 * SizeCountsPublic
 */
export type SizeCountsPublic = {
    /**
     * Data
     */
    data: Array<SizeCount>;
};

/**
 * SizeCreate
 */
export type SizeCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * SizePublic
 */
export type SizePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * SizeUpdate
 */
export type SizeUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * SizesPublic
 */
export type SizesPublic = {
    /**
     * Data
     */
    data: Array<SizePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Delivery Address
     */
    delivery_address?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Delivery Address
     */
    delivery_address?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Delivery Address
     */
    delivery_address?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Delivery Address
     */
    delivery_address?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WishlistItemCreate
 */
export type WishlistItemCreate = {
    /**
     * Item Id
     */
    item_id: string;
};

/**
 * WishlistItemPublic
 */
export type WishlistItemPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Item Id
     */
    item_id: string;
    item?: ItemPublic | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * WishlistItemsPublic
 */
export type WishlistItemsPublic = {
    /**
     * Data
     */
    data: Array<WishlistItemPublic>;
    /**
     * Count
     */
    count: number;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ItemsReadItemsPublicData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Category Id
         */
        category_id?: string | null;
        /**
         * Size Id
         */
        size_id?: string | null;
    };
    url: '/api/v1/items/public';
};

export type ItemsReadItemsPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsPublicError = ItemsReadItemsPublicErrors[keyof ItemsReadItemsPublicErrors];

export type ItemsReadItemsPublicResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsPublicResponse = ItemsReadItemsPublicResponses[keyof ItemsReadItemsPublicResponses];

export type ItemsReadItemPublicData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/public/{id}';
};

export type ItemsReadItemPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemPublicError = ItemsReadItemPublicErrors[keyof ItemsReadItemPublicErrors];

export type ItemsReadItemPublicResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemPublicResponse = ItemsReadItemPublicResponses[keyof ItemsReadItemPublicResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type ItemsDeleteItemPhotoData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/api/v1/items/{id}/photos';
};

export type ItemsDeleteItemPhotoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemPhotoError = ItemsDeleteItemPhotoErrors[keyof ItemsDeleteItemPhotoErrors];

export type ItemsDeleteItemPhotoResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsDeleteItemPhotoResponse = ItemsDeleteItemPhotoResponses[keyof ItemsDeleteItemPhotoResponses];

export type ItemsUploadItemPhotosData = {
    body: BodyItemsUploadItemPhotos;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}/photos';
};

export type ItemsUploadItemPhotosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUploadItemPhotosError = ItemsUploadItemPhotosErrors[keyof ItemsUploadItemPhotosErrors];

export type ItemsUploadItemPhotosResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUploadItemPhotosResponse = ItemsUploadItemPhotosResponses[keyof ItemsUploadItemPhotosResponses];

export type CategoriesReadCategoriesPublicData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/categories/public';
};

export type CategoriesReadCategoriesPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesReadCategoriesPublicError = CategoriesReadCategoriesPublicErrors[keyof CategoriesReadCategoriesPublicErrors];

export type CategoriesReadCategoriesPublicResponses = {
    /**
     * Successful Response
     */
    200: CategoriesPublic;
};

export type CategoriesReadCategoriesPublicResponse = CategoriesReadCategoriesPublicResponses[keyof CategoriesReadCategoriesPublicResponses];

export type CategoriesReadCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/categories/';
};

export type CategoriesReadCategoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesReadCategoriesError = CategoriesReadCategoriesErrors[keyof CategoriesReadCategoriesErrors];

export type CategoriesReadCategoriesResponses = {
    /**
     * Successful Response
     */
    200: CategoriesPublic;
};

export type CategoriesReadCategoriesResponse = CategoriesReadCategoriesResponses[keyof CategoriesReadCategoriesResponses];

export type CategoriesCreateCategoryData = {
    body: CategoryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type CategoriesCreateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesCreateCategoryError = CategoriesCreateCategoryErrors[keyof CategoriesCreateCategoryErrors];

export type CategoriesCreateCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesCreateCategoryResponse = CategoriesCreateCategoryResponses[keyof CategoriesCreateCategoryResponses];

export type CategoriesDeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/categories/{id}';
};

export type CategoriesDeleteCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesDeleteCategoryError = CategoriesDeleteCategoryErrors[keyof CategoriesDeleteCategoryErrors];

export type CategoriesDeleteCategoryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CategoriesDeleteCategoryResponse = CategoriesDeleteCategoryResponses[keyof CategoriesDeleteCategoryResponses];

export type CategoriesReadCategoryData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/categories/{id}';
};

export type CategoriesReadCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesReadCategoryError = CategoriesReadCategoryErrors[keyof CategoriesReadCategoryErrors];

export type CategoriesReadCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesReadCategoryResponse = CategoriesReadCategoryResponses[keyof CategoriesReadCategoryResponses];

export type CategoriesUpdateCategoryData = {
    body: CategoryUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/categories/{id}';
};

export type CategoriesUpdateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CategoriesUpdateCategoryError = CategoriesUpdateCategoryErrors[keyof CategoriesUpdateCategoryErrors];

export type CategoriesUpdateCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type CategoriesUpdateCategoryResponse = CategoriesUpdateCategoryResponses[keyof CategoriesUpdateCategoryResponses];

export type SizesReadSizesPublicData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/sizes/public';
};

export type SizesReadSizesPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SizesReadSizesPublicError = SizesReadSizesPublicErrors[keyof SizesReadSizesPublicErrors];

export type SizesReadSizesPublicResponses = {
    /**
     * Successful Response
     */
    200: SizesPublic;
};

export type SizesReadSizesPublicResponse = SizesReadSizesPublicResponses[keyof SizesReadSizesPublicResponses];

export type SizesReadSizeCountsPublicData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category Id
         */
        category_id?: string | null;
    };
    url: '/api/v1/sizes/counts/public';
};

export type SizesReadSizeCountsPublicErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SizesReadSizeCountsPublicError = SizesReadSizeCountsPublicErrors[keyof SizesReadSizeCountsPublicErrors];

export type SizesReadSizeCountsPublicResponses = {
    /**
     * Successful Response
     */
    200: SizeCountsPublic;
};

export type SizesReadSizeCountsPublicResponse = SizesReadSizeCountsPublicResponses[keyof SizesReadSizeCountsPublicResponses];

export type SizesReadSizesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/sizes/';
};

export type SizesReadSizesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SizesReadSizesError = SizesReadSizesErrors[keyof SizesReadSizesErrors];

export type SizesReadSizesResponses = {
    /**
     * Successful Response
     */
    200: SizesPublic;
};

export type SizesReadSizesResponse = SizesReadSizesResponses[keyof SizesReadSizesResponses];

export type SizesCreateSizeData = {
    body: SizeCreate;
    path?: never;
    query?: never;
    url: '/api/v1/sizes/';
};

export type SizesCreateSizeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SizesCreateSizeError = SizesCreateSizeErrors[keyof SizesCreateSizeErrors];

export type SizesCreateSizeResponses = {
    /**
     * Successful Response
     */
    200: SizePublic;
};

export type SizesCreateSizeResponse = SizesCreateSizeResponses[keyof SizesCreateSizeResponses];

export type SizesDeleteSizeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/sizes/{id}';
};

export type SizesDeleteSizeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SizesDeleteSizeError = SizesDeleteSizeErrors[keyof SizesDeleteSizeErrors];

export type SizesDeleteSizeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SizesDeleteSizeResponse = SizesDeleteSizeResponses[keyof SizesDeleteSizeResponses];

export type SizesReadSizeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/sizes/{id}';
};

export type SizesReadSizeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SizesReadSizeError = SizesReadSizeErrors[keyof SizesReadSizeErrors];

export type SizesReadSizeResponses = {
    /**
     * Successful Response
     */
    200: SizePublic;
};

export type SizesReadSizeResponse = SizesReadSizeResponses[keyof SizesReadSizeResponses];

export type SizesUpdateSizeData = {
    body: SizeUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/sizes/{id}';
};

export type SizesUpdateSizeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SizesUpdateSizeError = SizesUpdateSizeErrors[keyof SizesUpdateSizeErrors];

export type SizesUpdateSizeResponses = {
    /**
     * Successful Response
     */
    200: SizePublic;
};

export type SizesUpdateSizeResponse = SizesUpdateSizeResponses[keyof SizesUpdateSizeResponses];

export type CartClearCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cart/';
};

export type CartClearCartResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CartClearCartResponse = CartClearCartResponses[keyof CartClearCartResponses];

export type CartReadCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cart/';
};

export type CartReadCartResponses = {
    /**
     * Successful Response
     */
    200: CartItemsPublic;
};

export type CartReadCartResponse = CartReadCartResponses[keyof CartReadCartResponses];

export type CartAddCartItemData = {
    body: CartItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/cart/';
};

export type CartAddCartItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CartAddCartItemError = CartAddCartItemErrors[keyof CartAddCartItemErrors];

export type CartAddCartItemResponses = {
    /**
     * Successful Response
     */
    200: CartItemPublic;
};

export type CartAddCartItemResponse = CartAddCartItemResponses[keyof CartAddCartItemResponses];

export type CartDeleteCartItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/cart/{id}';
};

export type CartDeleteCartItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CartDeleteCartItemError = CartDeleteCartItemErrors[keyof CartDeleteCartItemErrors];

export type CartDeleteCartItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CartDeleteCartItemResponse = CartDeleteCartItemResponses[keyof CartDeleteCartItemResponses];

export type CartUpdateCartItemData = {
    body: CartItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/cart/{id}';
};

export type CartUpdateCartItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CartUpdateCartItemError = CartUpdateCartItemErrors[keyof CartUpdateCartItemErrors];

export type CartUpdateCartItemResponses = {
    /**
     * Successful Response
     */
    200: CartItemPublic;
};

export type CartUpdateCartItemResponse = CartUpdateCartItemResponses[keyof CartUpdateCartItemResponses];

export type WishlistReadWishlistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/wishlist/';
};

export type WishlistReadWishlistResponses = {
    /**
     * Successful Response
     */
    200: WishlistItemsPublic;
};

export type WishlistReadWishlistResponse = WishlistReadWishlistResponses[keyof WishlistReadWishlistResponses];

export type WishlistAddWishlistItemData = {
    body: WishlistItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/wishlist/';
};

export type WishlistAddWishlistItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WishlistAddWishlistItemError = WishlistAddWishlistItemErrors[keyof WishlistAddWishlistItemErrors];

export type WishlistAddWishlistItemResponses = {
    /**
     * Successful Response
     */
    200: WishlistItemPublic;
};

export type WishlistAddWishlistItemResponse = WishlistAddWishlistItemResponses[keyof WishlistAddWishlistItemResponses];

export type WishlistDeleteWishlistItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/wishlist/{id}';
};

export type WishlistDeleteWishlistItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WishlistDeleteWishlistItemError = WishlistDeleteWishlistItemErrors[keyof WishlistDeleteWishlistItemErrors];

export type WishlistDeleteWishlistItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type WishlistDeleteWishlistItemResponse = WishlistDeleteWishlistItemResponses[keyof WishlistDeleteWishlistItemResponses];

export type OrdersReadOrdersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: OrderStatus | null;
    };
    url: '/api/v1/orders/';
};

export type OrdersReadOrdersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrdersReadOrdersError = OrdersReadOrdersErrors[keyof OrdersReadOrdersErrors];

export type OrdersReadOrdersResponses = {
    /**
     * Successful Response
     */
    200: OrdersPublic;
};

export type OrdersReadOrdersResponse = OrdersReadOrdersResponses[keyof OrdersReadOrdersResponses];

export type OrdersCreateOrderData = {
    body: OrderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/orders/';
};

export type OrdersCreateOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrdersCreateOrderError = OrdersCreateOrderErrors[keyof OrdersCreateOrderErrors];

export type OrdersCreateOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type OrdersCreateOrderResponse = OrdersCreateOrderResponses[keyof OrdersCreateOrderResponses];

export type OrdersReadOrderData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/orders/{id}';
};

export type OrdersReadOrderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrdersReadOrderError = OrdersReadOrderErrors[keyof OrdersReadOrderErrors];

export type OrdersReadOrderResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type OrdersReadOrderResponse = OrdersReadOrderResponses[keyof OrdersReadOrderResponses];

export type OrdersUpdateOrderStatusData = {
    body: OrderUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/orders/{id}/status';
};

export type OrdersUpdateOrderStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrdersUpdateOrderStatusError = OrdersUpdateOrderStatusErrors[keyof OrdersUpdateOrderStatusErrors];

export type OrdersUpdateOrderStatusResponses = {
    /**
     * Successful Response
     */
    200: OrderPublic;
};

export type OrdersUpdateOrderStatusResponse = OrdersUpdateOrderStatusResponses[keyof OrdersUpdateOrderStatusResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};