"""items_replace_image_url_with_images_jsonb

Revision ID: 79731975e17a
Revises: b2c4d6e8f0a2
Create Date: 2026-05-15 15:54:13.537143

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79731975e17a'
down_revision = 'b2c4d6e8f0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_column('item', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('item', 'images')
    # ### end Alembic commands ###
