"""add_category_table_and_extend_item

Revision ID: e8e73185e6a6
Revises: fe56fa70289e
Create Date: 2026-05-07 15:48:07.596463

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e8e73185e6a6'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.add_column('item', sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('item', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.add_column('item', sa.Column('cost', sa.Numeric(precision=8, scale=2), nullable=True))
    op.create_foreign_key(None, 'item', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')  # ty: ignore[invalid-argument-type]
    op.drop_column('item', 'cost')
    op.drop_column('item', 'category_id')
    op.drop_column('item', 'brand')
    op.drop_column('item', 'size')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
