/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedCheckoutRouteImport } from './routes/_authed/checkout'
import { Route as AuthedCartRouteImport } from './routes/_authed/cart'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as PublicCatalogIndexRouteImport } from './routes/_public/catalog.index'
import { Route as PublicDocsTermsRouteImport } from './routes/_public/docs.terms'
import { Route as PublicDocsRefundRouteImport } from './routes/_public/docs.refund'
import { Route as PublicDocsPrivacyRouteImport } from './routes/_public/docs.privacy'
import { Route as PublicDocsDeliveryRouteImport } from './routes/_public/docs.delivery'
import { Route as PublicDocsContactsRouteImport } from './routes/_public/docs.contacts'
import { Route as PublicCatalogIdRouteImport } from './routes/_public/catalog.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckoutRoute = AuthedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCartRoute = AuthedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const PublicCatalogIndexRoute = PublicCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsTermsRoute = PublicDocsTermsRouteImport.update({
  id: '/docs/terms',
  path: '/docs/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsRefundRoute = PublicDocsRefundRouteImport.update({
  id: '/docs/refund',
  path: '/docs/refund',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsPrivacyRoute = PublicDocsPrivacyRouteImport.update({
  id: '/docs/privacy',
  path: '/docs/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsDeliveryRoute = PublicDocsDeliveryRouteImport.update({
  id: '/docs/delivery',
  path: '/docs/delivery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsContactsRoute = PublicDocsContactsRouteImport.update({
  id: '/docs/contacts',
  path: '/docs/contacts',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCatalogIdRoute = PublicCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminAdminRoute
  '/account': typeof AuthedAccountRoute
  '/cart': typeof AuthedCartRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/settings': typeof AuthedSettingsRoute
  '/catalog/$id': typeof PublicCatalogIdRoute
  '/docs/contacts': typeof PublicDocsContactsRoute
  '/docs/delivery': typeof PublicDocsDeliveryRoute
  '/docs/privacy': typeof PublicDocsPrivacyRoute
  '/docs/refund': typeof PublicDocsRefundRoute
  '/docs/terms': typeof PublicDocsTermsRoute
  '/catalog/': typeof PublicCatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminAdminRoute
  '/account': typeof AuthedAccountRoute
  '/cart': typeof AuthedCartRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/settings': typeof AuthedSettingsRoute
  '/catalog/$id': typeof PublicCatalogIdRoute
  '/docs/contacts': typeof PublicDocsContactsRoute
  '/docs/delivery': typeof PublicDocsDeliveryRoute
  '/docs/privacy': typeof PublicDocsPrivacyRoute
  '/docs/refund': typeof PublicDocsRefundRoute
  '/docs/terms': typeof PublicDocsTermsRoute
  '/catalog': typeof PublicCatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/cart': typeof AuthedCartRoute
  '/_authed/checkout': typeof AuthedCheckoutRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/catalog/$id': typeof PublicCatalogIdRoute
  '/_public/docs/contacts': typeof PublicDocsContactsRoute
  '/_public/docs/delivery': typeof PublicDocsDeliveryRoute
  '/_public/docs/privacy': typeof PublicDocsPrivacyRoute
  '/_public/docs/refund': typeof PublicDocsRefundRoute
  '/_public/docs/terms': typeof PublicDocsTermsRoute
  '/_public/catalog/': typeof PublicCatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/settings'
    | '/catalog/$id'
    | '/docs/contacts'
    | '/docs/delivery'
    | '/docs/privacy'
    | '/docs/refund'
    | '/docs/terms'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/settings'
    | '/catalog/$id'
    | '/docs/contacts'
    | '/docs/delivery'
    | '/docs/privacy'
    | '/docs/refund'
    | '/docs/terms'
    | '/catalog'
  id:
    | '__root__'
    | '/_admin'
    | '/_authed'
    | '/_public'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_admin/admin'
    | '/_authed/account'
    | '/_authed/cart'
    | '/_authed/checkout'
    | '/_authed/settings'
    | '/_public/'
    | '/_public/catalog/$id'
    | '/_public/docs/contacts'
    | '/_public/docs/delivery'
    | '/_public/docs/privacy'
    | '/_public/docs/refund'
    | '/_public/docs/terms'
    | '/_public/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checkout': {
      id: '/_authed/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthedCheckoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cart': {
      id: '/_authed/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthedCartRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/catalog/': {
      id: '/_public/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof PublicCatalogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/terms': {
      id: '/_public/docs/terms'
      path: '/docs/terms'
      fullPath: '/docs/terms'
      preLoaderRoute: typeof PublicDocsTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/refund': {
      id: '/_public/docs/refund'
      path: '/docs/refund'
      fullPath: '/docs/refund'
      preLoaderRoute: typeof PublicDocsRefundRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/privacy': {
      id: '/_public/docs/privacy'
      path: '/docs/privacy'
      fullPath: '/docs/privacy'
      preLoaderRoute: typeof PublicDocsPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/delivery': {
      id: '/_public/docs/delivery'
      path: '/docs/delivery'
      fullPath: '/docs/delivery'
      preLoaderRoute: typeof PublicDocsDeliveryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/contacts': {
      id: '/_public/docs/contacts'
      path: '/docs/contacts'
      fullPath: '/docs/contacts'
      preLoaderRoute: typeof PublicDocsContactsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/catalog/$id': {
      id: '/_public/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof PublicCatalogIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedCartRoute: typeof AuthedCartRoute
  AuthedCheckoutRoute: typeof AuthedCheckoutRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedCartRoute: AuthedCartRoute,
  AuthedCheckoutRoute: AuthedCheckoutRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCatalogIdRoute: typeof PublicCatalogIdRoute
  PublicDocsContactsRoute: typeof PublicDocsContactsRoute
  PublicDocsDeliveryRoute: typeof PublicDocsDeliveryRoute
  PublicDocsPrivacyRoute: typeof PublicDocsPrivacyRoute
  PublicDocsRefundRoute: typeof PublicDocsRefundRoute
  PublicDocsTermsRoute: typeof PublicDocsTermsRoute
  PublicCatalogIndexRoute: typeof PublicCatalogIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicCatalogIdRoute: PublicCatalogIdRoute,
  PublicDocsContactsRoute: PublicDocsContactsRoute,
  PublicDocsDeliveryRoute: PublicDocsDeliveryRoute,
  PublicDocsPrivacyRoute: PublicDocsPrivacyRoute,
  PublicDocsRefundRoute: PublicDocsRefundRoute,
  PublicDocsTermsRoute: PublicDocsTermsRoute,
  PublicCatalogIndexRoute: PublicCatalogIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
