/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as PublicCatalogRouteImport } from './routes/_public/catalog'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutCheckoutRouteImport } from './routes/_layout/checkout'
import { Route as LayoutCartRouteImport } from './routes/_layout/cart'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAccountRouteImport } from './routes/_layout/account'
import { Route as PublicCatalogIdRouteImport } from './routes/_public/catalog.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const PublicCatalogRoute = PublicCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PublicRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutRoute = LayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCartRoute = LayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountRoute = LayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutRoute,
} as any)
const PublicCatalogIdRoute = PublicCatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicCatalogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof LayoutAccountRoute
  '/admin': typeof LayoutAdminRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/settings': typeof LayoutSettingsRoute
  '/catalog': typeof PublicCatalogRouteWithChildren
  '/catalog/$id': typeof PublicCatalogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof LayoutAccountRoute
  '/admin': typeof LayoutAdminRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/settings': typeof LayoutSettingsRoute
  '/catalog': typeof PublicCatalogRouteWithChildren
  '/catalog/$id': typeof PublicCatalogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/account': typeof LayoutAccountRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/cart': typeof LayoutCartRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_public/catalog': typeof PublicCatalogRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_public/catalog/$id': typeof PublicCatalogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/settings'
    | '/catalog'
    | '/catalog/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/settings'
    | '/catalog'
    | '/catalog/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_public'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/account'
    | '/_layout/admin'
    | '/_layout/cart'
    | '/_layout/checkout'
    | '/_layout/settings'
    | '/_public/catalog'
    | '/_layout/'
    | '/_public/catalog/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_public/catalog': {
      id: '/_public/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof PublicCatalogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cart': {
      id: '/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoutCartRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account': {
      id: '/_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_public/catalog/$id': {
      id: '/_public/catalog/$id'
      path: '/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof PublicCatalogIdRouteImport
      parentRoute: typeof PublicCatalogRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccountRoute: typeof LayoutAccountRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCartRoute: typeof LayoutCartRoute
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountRoute: LayoutAccountRoute,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCartRoute: LayoutCartRoute,
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PublicCatalogRouteChildren {
  PublicCatalogIdRoute: typeof PublicCatalogIdRoute
}

const PublicCatalogRouteChildren: PublicCatalogRouteChildren = {
  PublicCatalogIdRoute: PublicCatalogIdRoute,
}

const PublicCatalogRouteWithChildren = PublicCatalogRoute._addFileChildren(
  PublicCatalogRouteChildren,
)

interface PublicRouteChildren {
  PublicCatalogRoute: typeof PublicCatalogRouteWithChildren
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCatalogRoute: PublicCatalogRouteWithChildren,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
